version: "3"

services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
  app:
    image: node:latest
    container_name: app
    restart: always
    env_file:
     - .env
    depends_on:
      - mongo
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    logging:
      driver: "json-file"
  